"""
It wasn’t a strawman. “What did the disciples see to be convinced Jesus was god” is in the same category as “who would die for a lie” – they both misunderstand history and how belief spreads. I didn’t “avoid answering”, you just have the memory of a goldfish. His followers didn’t “see something that convinced them he’d risen”, they misinterpreted his death as victory, which is also why his movement survived his death. But there’s no actual historical evidence they’ve seen anything or that they’ve proclaimed bodily resurrection immediately in Jerusalem, only later claims about experiences reported in partisan religious texts. Way to show your ignorance 🤣. Paul’s letters date to the mid 50s CE, not 34 CE. There’s no Roman or jewish confirmation of resurrection claims and no contemporary Jerusalem records of such.

You’re not doing any “minimal facts approach”, you’re doing a minimal thinking before spewing utter BS clown show of apologetics. What’s known by early non-christian sources like Celsus and Talmudic references is that Yeshua was seen as a charismatic wonder-worker and that multiple competing explanations existed. Calling him a sorcerer is not independent verification of supernatural power; it’s polemic. And if you think it’s enough to confirm without a doubt that actual supernatural miracles were performed, you’re more naive than a toddler walking into a stranger’s van for candy.

Out of all messianic figures of his time, whose movements died with them, Yeshua’s survived by cheating the system. And yes, I get you know about others like him, and that’s precisely my point. Of course people were expecting a messiah – that’s throughout the old testament, not just Enoch. In fact, second temple texts show multiple conflicting messianic expectations, not a single standalone doctrine. They also show divine agents aren’t the same as god reincarnate. And in case you forgot, the bible cannon was composed eventually – the early church cherry-picked texts and harmonized them after the fact. Nice self-own, you idiot 🤣. So unless you have a room temperature IQ (in Celsius. You know – the one where water freezes at 0 degrees and boils at 100), you can connect the dots and think “maybe all these people were attempting to fulfill OT prophecies about an upcoming savior and someone would’ve come out on top anyway”. The new testament is full of verses like “so that X prophecy may be fulfilled” and Yeshua is just the one that won.

Boy… tell me you don’t know christian history without telling me you don’t know christian history. Second temple judaism already included exalted humans (Enoch & Elijah), divine agents (Wisdom, Logos & Son of Man), heavenly vice-regents acting with god’s authority and all sorts of divine mediation. No early sources support your baseless assertion that “he was god”. High christology developed later, as per the gospel of John. Even Bart’s position isn’t in your favor, you total sadass 🤣. His position holds Jesus was quickly exalted, not immediately worshipped as co-equal to god in trinitarian terms. So I don’t care about your baseless assertions. Paul’s letters only show development of this view. You haven’t read Bart’s books and you don’t know his arguments. You couldn’t read the McDonald’s logo if your life depended on it. And it shows, given you’re supposed to read what I’ve said before replying.

LOL, talk about projection 🤣. You’re accusing me of strawman, yet you address the bereavement vision theory as if I’ve used it… But even still, bereavement hallucinations are common. You might not, but historians take them seriously. Group religious experiences are well-documented. Ever heard of mormon visions of the virgin Marry? On top of that, apocalyptic expectation amplifies interpretation and cognitive dissonance strengthens commitment after failed prophecy. A cult that believed Jesus would return ~1700’s only strengthened after the prediction failed, which is no surprise given your entire pathetic religion is based on denial and runs on cognitive dissonance like it’s oxygen. And that statistic is pulled out of your ass – no such data exists. Great argument, Einstein…

Paul had a guilty conscience out of killing off christians. It’s no surprise he experienced something he interpreted as visions of the risen christ. However, he places his experience in the same category as others’ visions and was already living in a vision-heavy apocalyptic jewish culture. He never met Yeshua. History’s full of hostile converts having religious experiences and we can only deduce Paul was sincere in his belief, not that he had a good reason to believe.

My bad… Sorry for misunderstanding your point about Origen, I just didn’t know your argument was that bad. All this shows is this accusation existed ~ the 3rd century and that early christians felt threatened by it. It doesn’t show the tomb was known, the body existed or that these claims were widespread ~30s CE. And the fact that Celsus was making this accusation doesn’t negate the fact that the gospels put the stories about Roman guards and Joseph of Arimathea to attempt to silence this criticism. Again – thinking that, for christianity to be false, the disciples must’ve stolen the body, is the most ridiculous typical christian strawman. There’s no historical grounding in “the empty tomb” narrative and your christian bias means nothing.

Precisely my point – Joseph of Arimathea is indeed ahistorical and the gospels mentioning him is just 1 way we know they’re historically unreliable. It’s not about “people at the time fact-checking any lies about him”, it’s about making him up conveniently for narrative purposes. What’s known is that Romans would sometimes indeed allow burials, that jewish law favored burial and that elite intermediaries could negotiate. That’s it – nothing about “Rome must comply, because they want to avoid a riot”. This is laughable. They were brutal tyrants, who’d suppress any uproar by Judea. For them, allowing burials was the exception. This mentality – that the Roman authorities would seek burial negotiations to avoid one, is the same naive wishful thinking used in the “who would die for a lie” argument – that the brutal murderers who crucified Jesus on a cross and allegedly put the martyrs through unimaginable tortures, would’ve let them go as long as they renounced Jesus as their lord and savior and that this would’ve been accurately documented. You’re not making this argument, but you might as well be. What isn’t verified is that Joseph of Arimathea was historical, that the tomb was public or known or that the burial story was anything more than theological symbolism. The story serves narrative and prophecy, appears in increasingly detailed form across gospels and fits theological needs perfectly.

You really are dumber than a sack of potatoes… Saying the gnostics weren’t christians is like saying catholics aren’t christians. Gnostics used Jesus, christian language and christian scripture and competed directly with proto-orthodoxy. They were declared non-christian after losing. I don’t know if you’ve ever heard this, but history’s written by the winners. And winners get to define labels. You buying into early orthodox propaganda shows you have the critical thinking skills of a burger.

Regarding apostolic succession: succession lists differ, teachings differed and early bishops disagreed sharply. Orthodoxy is retroactively defined and “Irenaeus says so” is not evidence. It’s an internal claim. Apostolic succession is theology, not history.

If you think the apocryphal gospels are dismissed as “late and unreliable”, wait till you learn about the cannon gospels – Mark’s written ~70 CE, Matthew and Luke ~80-85 CE and John – ~95 CE. All of them are written decades after the resurrection and none are written by eyewitnesses. They’re full of contradictions, but the early church simply cherry-picked the gospels based on how well they fit the narrative, not on internal consistency.

There were no eyewitness claims, only a claim by Paul that there were 500 eyewitnesses, 20 years after the event. Since you mentioned muslims, you might want to know how the quran says an entire town witnessed Muhammad flying on a winged horse to the Moon, splitting it in 2 such that each part is above the top of a different mountain. This is almost as ridiculous as christianity as a whole. I told you exactly what helped spread christianity until 313 CE. Don’t play dumb about it. Now you’re the one dodging my points.

“They all died” isn’t the win you wish it would be. Movements died when leaders died and political context shifted. Jesus’ movement survived because it reinterpreted failure as victory, spiritualized expectations, abandoned jewish nationalism, opened to Gentiles and de-emphasized the Torah. That’s adaptive theology, not divine validation. Simon bar Kochba failed because he tied success to military victory and didn’t get to redefine failure like Yeshua’s followers. Survival has nothing to do with truth. Islam, mormonism and cargo cults all survived.

No, letters, doctrine enforcement and martyr propaganda being used to spread christianity until 313 CE, along with appealing to marginalized people, is precisely my point. Paul’s epistles are literally the earliest christian sources we have. They’re used to correct doctrine, shame dissenters and assert authority. You already see boundary-drawing in Paul, 1 John and Ignatius: “Those people are false teachers”, “avoid them”, “hand them over to Satan”, etc. This is doctrine enforcement and it’s early, not late. And by the early 2nd century, martyrdom accounts were still being written, circulated, stylized and used pedagogically. Once again, you’re the one ignoring my points.

How you thought “if it appears as a miracle, it must be” is beyond me. I bet that street magician must’ve used magic to make you that retarded. Ancient people interpreted events through supernatural frameworks by default.

While Romans would sometimes adopt to local customs when it suited imperial stability, that doesn’t mean Roman prefects adopted jewish ritual gestures, Roman legal officials performed symbolic absolution rites or that Pilate specifically did anything similar. The hand-washing scene in Matthew mirrors Deuteronomy 21:6-7 almost verbatim in symbolic logic. It doesn’t appear in the earliest gospel Mark, it has no basis in Roman legal practice and it fits Matthew’s broader pattern of “fulfillment” storytelling. I never said Matthew quotes Deuteronomy – that’s part of the point. It obviously won’t do that, but the parallel is obvious. It’s not “Pilate respecting jewish customs”, it’s Matthew rewriting responsibility away from Rome and onto the jews. That’s the scholarly consensus and you’re just a crybaby who won’t accept it. I’m not the one making up an ahistorical version of Pilate. He was a violent contemptuous administrator, who got recalled to Rome for excessive brutality. The gospels progressively sanding him down is damage control and actually has no backing.

I bet you jerk yourself off to the claim that “christianity invented charity, hospitals and moral standards”. Judaism and pagan benefaction had charity before christianity. Hospitals as institutions develop much later and under many influences, including Roman civic structures and islamic medicine. Christianity only systematized care within its communities, which helped growth. And don’t talk about infanticide. It reminds me of my favorite Psalm – “Happy is he who takes their little ones and bashes their skulls against the rocks”. And no, infanticide didn’t end because of christians. It was already morally contested in Greco-Roman philosophy and while christians opposed it, they didn’t end it by argument alone. Bart acknowledges christians opposed infanticide, just like some chrsitians by exception opposed slavery when it was still normalized.

It’s not that “atheist regimes killed >100 million people”. An “atheist regime” isn’t a coherent category. Such regimes have killed for authoritarian, nationalist or ideological reasons. Religion was just replaced by state dogma, which isn’t much better, seeing as how religion and politics always went hand-by-hand. And don’t forget about all your religious wars, inquisitions, crusades, witch hunts, colonial atrocities and forced conversions. These are all on your camp.

Now take responsibility and apologize. Not for all that, but for the utter condom fail you’ve become. No wonder you’re against abortion – you’re the ultimate abortion fail too.

In case you want to know, none of the arguments you’ve presented demonstrate christianity or are even taken seriously by experts. These and a lot more are covered in this document I’ve been writing on christianity:
https://docs.google.com/document/d/18_iu0D2pqDF0lHuWA5SWkDGPoSIZQZEILJtBiZKaNoI/edit?pli=1&tab=t.0
here, educate yourself. Disappointment.
"""
